### ISSUE TITLE
Unable to import module 'src/lambda_handler': No module named 'onnxruntime.capi.onnxruntime_pybind11_state'

### ISSUE THREAD

**Issue by oscarchan76** [adrien-glg/onnx-decomposer_aws#1]
hello, i use  your readme.md file to deploy the onnx-decomposer_aws project. 
However, i have a problem ,when exec ./invoke_lambda_function.sh -l 0, but the message return is following as,

(venv) [ec2-user@ip-172-31-18-206 lambda_scripts]$ ./invoke_lambda_function.sh -l 0
{
    "StatusCode": 200,
    "FunctionError": "Unhandled",
    "ExecutedVersion": "$LATEST"
}
{
  "errorMessage": "Unable to import module 'src/lambda_handler': No module named 'onnxruntime.capi.onnxruntime_pybind11_state'",
  "errorType": "Runtime.ImportModuleError",
  "stackTrace": []
}

so, i dont know how to fix this problem.

Can you give me some suggestions?

Thank you.

**Comment by adrien-glg** [comment]
Hi Oscar,
It looks like something went wrong when you created the Lambda deployment package, because onnxruntime is missing.
Let's consider the MobileDet model as an example.
Can you check that `lambda_code/projects/mobiledet/mobiledet_lambda_requirements.txt` is as follows:
```
numpy
onnxruntime==1.15.1
onnx
protobuf==3.20.2
```
Then, when creating the deployment package, it's important that you make sure you get no errors in the process.
Let me know if that solved your problem.

**Comment by oscarchan76** [comment]
Hi Adrien,

Thanks ! 
The problem has already solved. I think the problem caused:
1.The environment that make deployment package is different from the `AWS lambda`(`Python 3.8`)，i don't notice the runtime of `Amazon Linux2` is `Python3.9`
2.Due to the latest `onnxruntime` requires set `providers = ["AzureExecutionProvider", "CPUExecutionProvider"]` when invoke method `InferenceSession`, I modify the source code of `first_slice.py` and `other_slice.py`. It maybe affects the deployment.

And I also has a question:
You add the input file (xxxx.png) into the deployment package, and invoke function to exec inference. I wonder if it is possible to separate the input file from the deployment package and then pass the input file (e.g. xxxx.png) to the function when invoked to perform inference.

I hope you can give me some suggestions.

**Comment by adrien-glg** [comment]
Hi Oscar,
Good to hear that you managed to solve the problem.
Regarding the input file, what you are mentioning is definitely possible but hasn't been implemented. A typical execution would be as follows:
- the input file is uploaded to S3
- the Lambda function fetches the file from S3
- the inference is performed.

This would require a few code modifications to support this feature. Other solutions might be possible as well.

**Comment by oscarchan76** [comment]
Thanks！
